document.addEventListener("DOMContentLoaded", function(){
  const canvas = document.getElementById('mycanvas');
  canvas.height = 500;
  canvas.width = 500;
  const ctx = canvas.getContext('2d');
  ctx.fillStyle = 'red';
  ctx.fillRect(0, 0, 500, 500);
  ctx.beginPath();
  ctx.arc(250, 250, 100, 0, 360);
  ctx.strokeStyle = 'black';
  ctx.lineWidth = 4;
  ctx.stroke();
  ctx.fillStyle = 'PapayaWhip';
  ctx.fill();
  ctx.beginPath();
  ctx.moveTo(75, 50);
  ctx.lineTo(200, 150);
  ctx.lineTo(200, 25);
  ctx.fillStyle = 'white';
  ctx.fill();
});
